set ignore-comments

alias s := server
alias serve := server
alias b := build

default:
  just --list

server:
  hugo server -D --source ./exampleSite --themesDir ../..

build:
  hugo --minify --gc --printI18nWarnings --printPathWarnings --panicOnWarning --destination ../public --source ./exampleSite --themesDir ../.. --baseURL https://maolonglong.github.io/hugo-simple/

fmt:
  git ls-files --cached --others --exclude-standard -z '*.toml' | xargs -0 taplo fmt
  bun run fmt

check:
  git ls-files --cached --others --exclude-standard -z '*.toml' | xargs -0 taplo fmt --check
  bun run check

# Regenerate the class-based code highlighting CSS (light + dark) from two Chroma styles.
chroma light="github" dark="github-dark":
  #!/usr/bin/env sh
  set -eu
  strip() {
    css=$(hugo gen chromastyles --style="$1")
    printf '%s\n' "$css" |
      sed -e '/^\/\* Generated/d' -e '/^\/\* Background \*\//d' \
        -e 's,^/\* PreWrapper \*/ .*,.chroma { -webkit-text-size-adjust:none; },' \
        -e 's,^/\* [^*]* \*/ ,,' -e '/^$/d'
  }
  # Generate both palettes before touching the output so a bad style name fails cleanly.
  light_css=$(strip "{{light}}")
  dark_css=$(strip "{{dark}}")
  {
    echo '/* Generated by `just chroma`: "{{light}}" (light) and "{{dark}}" (dark). Do not edit. */'
    echo '/* Each palette is scoped to its own scheme so classes missing from one never leak into the other. */'
    echo '@media not all and (prefers-color-scheme: dark) {'
    printf '%s\n' "$light_css" | sed 's/^/  /'
    echo '}'
    echo '@media (prefers-color-scheme: dark) {'
    printf '%s\n' "$dark_css" | sed 's/^/  /'
    echo '}'
  } > assets/chroma.css.tmp
  mv assets/chroma.css.tmp assets/chroma.css

update-simplecss:
  curl -fSL https://cdn.simplecss.org/simple.css -o ./assets/simple.css

clean:
  rm -r public
