set ignore-comments

alias s := server
alias serve := server
alias b := build

default:
  just --list

server:
  hugo server -D --source ./exampleSite --themesDir ../..

build:
  hugo --minify --gc --printI18nWarnings --printPathWarnings --panicOnWarning --destination ../public --source ./exampleSite --themesDir ../.. --baseURL https://maolonglong.github.io/hugo-simple/

fmt:
  # TODO: https://github.com/numtide/treefmt-nix/issues/112
  nix fmt
  bun run fmt

check:
  # TODO: https://github.com/numtide/treefmt-nix/issues/112
  nix flake check
  bun run check

# Regenerate the class-based code highlighting CSS (light + dark) from two Chroma styles.
chroma light="github" dark="github-dark":
  #!/usr/bin/env sh
  set -eu
  strip() {
    hugo gen chromastyles --style="$1" |
      sed -e '/^\/\* Generated/d' -e '/^\/\* Background \*\//d' \
        -e 's,^/\* PreWrapper \*/ .*,.chroma { -webkit-text-size-adjust:none; },' \
        -e 's,^/\* [^*]* \*/ ,,' -e '/^$/d'
  }
  {
    echo '/* Generated by `just chroma`: "{{light}}" (light) and "{{dark}}" (dark). Do not edit. */'
    echo '/* Each palette is scoped to its own scheme so classes missing from one never leak into the other. */'
    echo '@media not all and (prefers-color-scheme: dark) {'
    strip "{{light}}" | sed 's/^/  /'
    echo '}'
    echo '@media (prefers-color-scheme: dark) {'
    strip "{{dark}}" | sed 's/^/  /'
    echo '}'
  } > assets/chroma.css

update-simplecss:
  curl -fSL https://cdn.simplecss.org/simple.css -o ./assets/simple.css

clean:
  rm -r public
